project_id = "ppvifagplcdjpdpqknzt"

[functions.scout-chat]
verify_jwt = false

[functions.scout-assistant]
verify_jwt = true

[functions.generate-sitemap]
verify_jwt = false

[functions.generate-rss]
verify_jwt = false

[functions.generate-recommendations]
verify_jwt = true

[functions.assign-smart-tags]
verify_jwt = true

[functions.publish-scheduled-articles]
verify_jwt = true

[functions.map-csv-categories]
verify_jwt = true

[functions.notify-new-comment]
verify_jwt = true

[functions.generate-article-comments]
verify_jwt = true

[functions.auto-comment-new-articles]
verify_jwt = true

[functions.generate-tldr-snapshot]
verify_jwt = true

[functions.assign-article-category]
verify_jwt = true

[functions.download-and-upload-image]
verify_jwt = true
