project_id = "ppvifagplcdjpdpqknzt"

[functions.scout-chat]
verify_jwt = false

[functions.scout-assistant]
verify_jwt = true

[functions.generate-sitemap]
verify_jwt = false

[functions.publish-scheduled-articles]
verify_jwt = false

[functions.map-csv-categories]
verify_jwt = false

[functions.notify-new-comment]
verify_jwt = false
